### ISSUE TITLE
WebSocket server crashed

### ISSUE THREAD

**Issue by Gicminos** [deStrO/eBot-CSGO#115]
php bootstrap.php
```
-----------------------------------------------------
| PHP 5.3.1 or newer    -> required  -> [ Yes ] 5.6.27
| Standard PHP Library  -> required  -> [ Yes ]
| MySQL                 -> required  -> [ Yes ]
| Sockets               -> required  -> [ Yes ]
| pthreads              -> required  -> [ Yes ]
-----------------------------------------------------
| Registerung Shutdown function !
| Starting eBot Websocket-Server !
| Using node
| WebSocket server crashed
-----------------------------------------------------
```
All config is correct... I don't know how to resolve this.

**Comment by Nols1000** [comment]
Try to run the node Server in a own instance and post the error message here. Run it with the command: `node websocket_server.js [bot_ip] [bot_port]` in your eBot root directory. What system are you running the eBot? What noder version are you using?

**Comment by Gicminos** [comment]
This is the output:

```
    info  - socket.io started
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: bind EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at dgram.js:224:28
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

```

I'm using Debian 7 and node version 0.12.18

**Comment by Nols1000** [comment]
Look's like the port the bot is using is reserved by another program I dont exactly know which port it's using. Try to find out the port in the websocket_bot.js. Vor wait for me to get my PC and find it out.

**Comment by Nols1000** [comment]
Try to change the port in config.ini.smp or try to find the blocking background process.

**Comment by Gicminos** [comment]
Resolved this, now I've got another error:

```
/home/ebot/ebot-csgo/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/home/ebot/ebot-csgo/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ebot/ebot-csgo/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:571:32)

```

**Comment by Nols1000** [comment]
What node version are you using. Maby try Bode 0.10.x.

**Comment by Gicminos** [comment]
Using Node 0.10.48 resolved this issue. Very thank you.
